<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    <title>MLNBOOK</title>
</head>
<body>
    <h2>MLNBOOK</h2>
    <p>This is a guest book powered by mlnphp framework. copyrights (C) <?php $this->put($author)?></p>
</body>
</html>